// Gallery Photo Data
const galleryPhotos = [
    // Futebol
    {
        id: 1,
        title: "Final do Campeonato Estadual",
        description: "Momento decisivo da final que definiu o campeão estadual. Tensão e emoção em cada lance.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=1",
        date: "2024-01-15",
        location: "Estádio Nacional",
        event: "Campeonato Estadual 2024",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 1600",
        tags: ["final", "campeonato", "gol", "emoção"],
        featured: true,
        favorited: false
    },
    {
        id: 2,
        title: "Cobrança de Falta Perfeita",
        description: "Lance técnico que resultou em um golaço de falta. Precisão e elegância em campo.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=2",
        date: "2024-01-12",
        location: "Arena Municipal",
        event: "Liga Regional",
        camera: "Canon EOS R5",
        settings: "1/800s, f/4.0, ISO 800",
        tags: ["falta", "gol", "técnica"],
        featured: false,
        favorited: false
    },
    {
        id: 3,
        title: "Defesa Espetacular",
        description: "Goleiro fazendo uma defesa impossível que salvou o time na partida decisiva.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=3",
        date: "2024-01-10",
        location: "Estádio Central",
        event: "Copa da Cidade",
        camera: "Canon EOS R5",
        settings: "1/1250s, f/2.8, ISO 1200",
        tags: ["defesa", "goleiro", "salvamento"],
        featured: false,
        favorited: false
    },

    // Basquete
    {
        id: 4,
        title: "Enterrada Espetacular",
        description: "Lance épico durante partida do NBB. Força e agilidade em perfeita sincronia.",
        category: "basquete",
        image: "https://picsum.photos/800/600?random=4",
        date: "2024-01-14",
        location: "Ginásio Olímpico",
        event: "NBB 2024",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 2000",
        tags: ["enterrada", "NBB", "espetacular"],
        featured: true,
        favorited: false
    },
    {
        id: 5,
        title: "Arremesso de Três",
        description: "Momento exato do arremesso de três pontos que decidiu a partida nos últimos segundos.",
        category: "basquete",
        image: "https://picsum.photos/800/600?random=5",
        date: "2024-01-11",
        location: "Arena Esportiva",
        event: "Campeonato Metropolitano",
        camera: "Canon EOS R5",
        settings: "1/800s, f/3.5, ISO 1600",
        tags: ["três pontos", "decisivo", "clutch"],
        featured: false,
        favorited: false
    },
    {
        id: 6,
        title: "Disputa no Garrafão",
        description: "Intensa disputa de rebote mostrando a força e determinação dos atletas.",
        category: "basquete",
        image: "https://picsum.photos/800/600?random=6",
        date: "2024-01-08",
        location: "Complexo Esportivo",
        event: "Liga Universitária",
        camera: "Canon EOS R5",
        settings: "1/640s, f/4.0, ISO 1400",
        tags: ["rebote", "disputa", "força"],
        featured: false,
        favorited: false
    },

    // Vôlei
    {
        id: 7,
        title: "Ataque Potente",
        description: "Cortada devastadora que fechou o set. Potência e precisão em cada movimento.",
        category: "volei",
        image: "https://picsum.photos/800/600?random=7",
        date: "2024-01-13",
        location: "Ginásio Central",
        event: "Superliga Feminina",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 1800",
        tags: ["cortada", "ataque", "potência"],
        featured: true,
        favorited: false
    },
    {
        id: 8,
        title: "Defesa Impossível",
        description: "Manchete salvadora que manteve a equipe viva no rally mais longo da partida.",
        category: "volei",
        image: "https://picsum.photos/800/600?random=8",
        date: "2024-01-09",
        location: "Arena Vôlei",
        event: "Copa Nacional",
        camera: "Canon EOS R5",
        settings: "1/800s, f/3.2, ISO 1600",
        tags: ["defesa", "manchete", "salvamento"],
        featured: false,
        favorited: false
    },
    {
        id: 9,
        title: "Bloqueio Duplo",
        description: "Coordenação perfeita no bloqueio que frustrou o ataque adversário.",
        category: "volei",
        image: "https://picsum.photos/800/600?random=9",
        date: "2024-01-07",
        location: "Quadra Poliesportiva",
        event: "Torneio Estadual",
        camera: "Canon EOS R5",
        settings: "1/1250s, f/2.8, ISO 1200",
        tags: ["bloqueio", "coordenação", "defesa"],
        featured: false,
        favorited: false
    },

    // Natação
    {
        id: 10,
        title: "Chegada Épica",
        description: "Disputa acirrada nos últimos metros dos 100m livre. Cada centésimo importa.",
        category: "natacao",
        image: "https://picsum.photos/800/600?random=10",
        date: "2024-01-16",
        location: "Centro Aquático",
        event: "Campeonato Nacional",
        camera: "Canon EOS R5",
        settings: "1/1600s, f/2.8, ISO 800",
        tags: ["chegada", "velocidade", "disputa"],
        featured: true,
        favorited: false
    },
    {
        id: 11,
        title: "Borboleta Perfeita",
        description: "Técnica impecável no nado borboleta, demonstrando anos de dedicação e treino.",
        category: "natacao",
        image: "https://picsum.photos/800/600?random=11",
        date: "2024-01-14",
        location: "Piscina Olímpica",
        event: "Troféu Brasil",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/3.5, ISO 1000",
        tags: ["borboleta", "técnica", "elegância"],
        featured: false,
        favorited: false
    },
    {
        id: 12,
        title: "Largada Explosiva",
        description: "Momento da largada mostrando a explosão e sincronismo dos nadadores.",
        category: "natacao",
        image: "https://picsum.photos/800/600?random=12",
        date: "2024-01-12",
        location: "Complexo Aquático",
        event: "Open de Natação",
        camera: "Canon EOS R5",
        settings: "1/2000s, f/2.8, ISO 640",
        tags: ["largada", "explosão", "sincronismo"],
        featured: false,
        favorited: false
    },

    // Tênis
    {
        id: 13,
        title: "Saque Perfeito",
        description: "Precisão e técnica no saque que definiu o match point. Concentração total.",
        category: "tenis",
        image: "https://picsum.photos/800/600?random=13",
        date: "2024-01-15",
        location: "Tennis Club",
        event: "Torneio Open",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 1200",
        tags: ["saque", "precisão", "match point"],
        featured: true,
        favorited: false
    },
    {
        id: 14,
        title: "Forehand Devastador",
        description: "Golpe de direita com potência e precisão que surpreendeu o adversário.",
        category: "tenis",
        image: "https://picsum.photos/800/600?random=14",
        date: "2024-01-13",
        location: "Centro de Tênis",
        event: "Circuit Pro",
        camera: "Canon EOS R5",
        settings: "1/800s, f/4.0, ISO 1600",
        tags: ["forehand", "potência", "winner"],
        featured: false,
        favorited: false
    },
    {
        id: 15,
        title: "Voleio Espetacular",
        description: "Jogada na rede que mostrou reflexos rápidos e técnica apurada.",
        category: "tenis",
        image: "https://picsum.photos/800/600?random=15",
        date: "2024-01-11",
        location: "Quadra Central",
        event: "Challenger",
        camera: "Canon EOS R5",
        settings: "1/1250s, f/2.8, ISO 1400",
        tags: ["voleio", "reflexo", "rede"],
        featured: false,
        favorited: false
    },

    // Corrida
    {
        id: 16,
        title: "Sprint Final",
        description: "Explosão final nos últimos 100 metros da maratona. Determinação pura.",
        category: "corrida",
        image: "https://picsum.photos/800/600?random=16",
        date: "2024-01-14",
        location: "Circuito Urbano",
        event: "Maratona da Cidade",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 800",
        tags: ["sprint", "final", "maratona"],
        featured: true,
        favorited: false
    },
    {
        id: 17,
        title: "Ultrapassagem Decisiva",
        description: "Momento exato da ultrapassagem que mudou o rumo da corrida.",
        category: "corrida",
        image: "https://picsum.photos/800/600?random=17",
        date: "2024-01-12",
        location: "Pista de Atletismo",
        event: "Meeting de Atletismo",
        camera: "Canon EOS R5",
        settings: "1/800s, f/3.5, ISO 1000",
        tags: ["ultrapassagem", "velocidade", "estratégia"],
        featured: false,
        favorited: false
    },
    {
        id: 18,
        title: "Salto com Obstáculos",
        description: "Técnica perfeita na passagem do obstáculo durante a corrida de 3000m.",
        category: "corrida",
        image: "https://picsum.photos/800/600?random=18",
        date: "2024-01-10",
        location: "Estádio Olímpico",
        event: "Campeonato de Atletismo",
        camera: "Canon EOS R5",
        settings: "1/1600s, f/2.8, ISO 1200",
        tags: ["obstáculos", "técnica", "salto"],
        featured: false,
        favorited: false
    },

    // Fotos adicionais para completar o dataset
    {
        id: 19,
        title: "Comemoração Épica",
        description: "Momento de pura emoção após o gol da vitória no último minuto.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=19",
        date: "2024-01-06",
        location: "Arena do Povo",
        event: "Derby Local",
        camera: "Canon EOS R5",
        settings: "1/500s, f/2.8, ISO 2000",
        tags: ["comemoração", "emoção", "vitória"],
        featured: false,
        favorited: false
    },
    {
        id: 20,
        title: "Lance Livre Decisivo",
        description: "Concentração total antes do arremesso que decidiu o jogo.",
        category: "basquete",
        image: "https://picsum.photos/800/600?random=20",
        date: "2024-01-05",
        location: "Ginásio Municipal",
        event: "Final Regional",
        camera: "Canon EOS R5",
        settings: "1/400s, f/2.8, ISO 2500",
        tags: ["lance livre", "concentração", "decisivo"],
        featured: false,
        favorited: false
    },
    {
        id: 21,
        title: "Saque Ace",
        description: "Saque direto que não deu chance para a defesa adversária reagir.",
        category: "volei",
        image: "https://picsum.photos/800/600?random=21",
        date: "2024-01-04",
        location: "Quadra Coberta",
        event: "Liga Juvenil",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/3.2, ISO 1800",
        tags: ["saque", "ace", "potência"],
        featured: false,
        favorited: false
    },
    {
        id: 22,
        title: "Mergulho Perfeito",
        description: "Entrada na água com técnica impecável na prova de mergulho.",
        category: "natacao",
        image: "https://picsum.photos/800/600?random=22",
        date: "2024-01-03",
        location: "Centro Aquático Nacional",
        event: "Campeonato de Mergulho",
        camera: "Canon EOS R5",
        settings: "1/2000s, f/2.8, ISO 400",
        tags: ["mergulho", "técnica", "precisão"],
        featured: false,
        favorited: false
    },
    {
        id: 23,
        title: "Backhand Cross Court",
        description: "Golpe de esquerda cruzado que surpreendeu o adversário na rede.",
        category: "tenis",
        image: "https://picsum.photos/800/600?random=23",
        date: "2024-01-02",
        location: "Clube de Tênis Elite",
        event: "Torneio Master",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/4.0, ISO 1600",
        tags: ["backhand", "cruzado", "precisão"],
        featured: false,
        favorited: false
    },
    {
        id: 24,
        title: "Largada dos 100m",
        description: "Explosão na largada da prova mais rápida do atletismo mundial.",
        category: "corrida",
        image: "https://picsum.photos/800/600?random=24",
        date: "2024-01-01",
        location: "Pista Olímpica",
        event: "Meeting Internacional",
        camera: "Canon EOS R5",
        settings: "1/2000s, f/2.8, ISO 800",
        tags: ["largada", "100m", "velocidade"],
        featured: false,
        favorited: false
    },

    // Fotos adicionais para enriquecer o portfólio
    {
        id: 25,
        title: "Cabeceio Certeiro",
        description: "Gol de cabeça após cruzamento perfeito da lateral direita.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=25",
        date: "2023-12-30",
        location: "Estádio Municipal",
        event: "Copa Regional",
        camera: "Canon EOS R5",
        settings: "1/800s, f/2.8, ISO 1400",
        tags: ["cabeceio", "gol", "cruzamento"],
        featured: false,
        favorited: false
    },
    {
        id: 26,
        title: "Drible Desconcertante",
        description: "Jogada individual que deixou três marcadores para trás.",
        category: "futebol",
        image: "https://picsum.photos/800/600?random=26",
        date: "2023-12-28",
        location: "Campo do Clube",
        event: "Amistoso Internacional",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/3.5, ISO 1600",
        tags: ["drible", "habilidade", "individual"],
        featured: false,
        favorited: false
    },
    {
        id: 27,
        title: "Passagem de Bastão",
        description: "Sincronia perfeita no revezamento 4x100m feminino.",
        category: "corrida",
        image: "https://picsum.photos/800/600?random=27",
        date: "2023-12-26",
        location: "Pista do Ibirapuera",
        event: "Troféu Brasil de Atletismo",
        camera: "Canon EOS R5",
        settings: "1/1250s, f/2.8, ISO 1000",
        tags: ["revezamento", "bastão", "sincronismo"],
        featured: false,
        favorited: false
    },
    {
        id: 28,
        title: "Costas Olímpico",
        description: "Técnica impecável no nado de costas durante a final dos 200m.",
        category: "natacao",
        image: "https://picsum.photos/800/600?random=28",
        date: "2023-12-24",
        location: "Parque Aquático",
        event: "Seletiva Olímpica",
        camera: "Canon EOS R5",
        settings: "1/1000s, f/2.8, ISO 1200",
        tags: ["costas", "técnica", "olímpico"],
        featured: false,
        favorited: false
    },
    {
        id: 29,
        title: "Smash Definitivo",
        description: "Cortada que fechou o primeiro set com autoridade absoluta.",
        category: "tenis",
        image: "https://picsum.photos/800/600?random=29",
        date: "2023-12-22",
        location: "Quadra Saibro",
        event: "Clay Court Championship",
        camera: "Canon EOS R5",
        settings: "1/800s, f/2.8, ISO 1800",
        tags: ["smash", "potência", "definitivo"],
        featured: false,
        favorited: false
    },
    {
        id: 30,
        title: "Levantada Milimétrica",
        description: "Passe perfeito que criou a oportunidade para o ataque vencedor.",
        category: "volei",
        image: "https://picsum.photos/800/600?random=30",
        date: "2023-12-20",
        location: "Ginásio Poliesportivo",
        event: "Superliga Masculina",
        camera: "Canon EOS R5",
        settings: "1/640s, f/3.5, ISO 1600",
        tags: ["levantada", "passe", "precisão"],
        featured: false,
        favorited: false
    }
];

// Export for use in gallery.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = galleryPhotos;
}